version: "3"
services:
  ms-sql-server:
    image: justin2004/mssql_server_tiny
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "xxxxxxx"
    ports:
      - "1433:1433"
  catalog-api:
    build: .
    ports:
      - "8080:80"
